### ISSUE TITLE
Test for test_log_in_view() is failing

### ISSUE THREAD

**Issue by Kyal-Patel** [LMarshallAfzal/SEG-small-group-project#1]
@Kyal-Patel is currently working to fix the failed tests, however, is unable to resolve the last failed test, test_successful_log_in() - the test failed when asserting that the user is logged in, meaning there is an issue with the validation process. 

@Kyal-Patel is requesting help from @LMarshallAfzal (who created the validation process) to solve this failed test.

**Comment by VimVoyager** [comment]
@Kyal-Patel Can you explain what you changed when testing for this as it passes on my end.

**Comment by Kyal-Patel** [comment]
@LMarshallAfzal I've realised the tests fail on my side as I have no data in my database, therefore there are no users to check against and login to the system. If the tests pass on your end, then we just need to add some users to the database and it should pass for me too.

**Comment by VimVoyager** [comment]
@Kyal-Patel I have just realised I forgot about the seeder, let me implement that then merge with main, gimme like like 20 minutes

**Comment by VimVoyager** [comment]
@Kyal-Patel I have I have added a seeder and unseeder to add values to the database. On my end that also fails now, I think it is to do with the redirect to the non existent feed.html. So until we add the new html, we may have to leave that one.
