### ISSUE TITLE
When logging in email is case sensitive which it shouldn't be

### ISSUE THREAD

**Issue by VimVoyager** [LMarshallAfzal/SEG-small-group-project#19]
@VinceWuu @Guneek @ZaidMaraqa @Kyal-Patel I noticed a bug in the sign up form that meaning that the email is case sensitive. I don't think this should be the case. So we need to change that so that when the email is first added to the database it added in lowercase. when it is typed into log in users should be allowed to use what ever case they want and it should not matter.

**Comment by Guneek** [comment]
I'll change it to include .toLower() on both adding to DB and after it is typed in.

**Comment by Guneek** [comment]
fixed
