### ISSUE TITLE
How to test experience_level attribute of User model?

### ISSUE THREAD

**Issue by Kyal-Patel** [LMarshallAfzal/SEG-small-group-project#2]
(Title). The user model tests have been made in the user-model-tests branch, with a missing section for the experience_level user tests.

**Comment by VimVoyager** [comment]
I just put experience level there as a placeholder if you read through the rest of the epics it shows it cannot stay this simplistic. There need to be a numerical value put to do the calculations. You can make changes to experience level in user model to do it correctly.

**Comment by Kyal-Patel** [comment]
@LMarshallAfzal I couldn't see anything on experience level having to be more complex. If you are referring to elo, this could be a separate metric, where experience level is a reference to how long they have been playing rather than how good they are.

**Comment by Guneek** [comment]
@Kyal-Patel, @LMarshallAfzal Elo is a separate metric, as it changes from match to match and says the changes of Elo from match to match on their profile [check the last epic]
