### ISSUE TITLE
Cannot promote a member to officer in a club

### ISSUE THREAD

**Issue by VinceWuu** [LMarshallAfzal/SEG-small-group-project#20]
![image](https://user-images.githubusercontent.com/51149363/145442762-59b637f1-2d40-4d50-a2dd-78509ad8ebf1.png)

**Comment by VimVoyager** [comment]
@VinceWuu I'll get on that, I know what to do.

**Comment by VimVoyager** [comment]
@VinceWuu All fixed now. Turns out the function call was just missing brackets.
