### ISSUE TITLE
Owner member list view is empty when using class based view

### ISSUE THREAD

**Issue by Guneek** [LMarshallAfzal/SEG-small-group-project#22]
Came across an issue with owner member list view being empty when trying to turn it into a class based view. Whether inheriting from officerlistview, memberlistview or list view, it is always blank when running the server and opening it.

**Comment by VimVoyager** [comment]
@Guneek Can you comment with a screenshot of your issue, because I tried that on my end and it seems to be fine.

**Comment by Guneek** [comment]
<img width="400" alt="Screenshot 2021-12-11 at 10 36 38" src="https://user-images.githubusercontent.com/60737783/145673722-176904eb-2d58-4c68-8f72-3c53717bb2e7.png">

**Comment by Guneek** [comment]
This is the owner class-based view using inheritance from the officer list view (which works) but when loaded up it just comes up with a blank page. In theory, it should work since it's just inheriting methods from the officer list view. 

The officer list view inherits from the member list view in a very similar way and works completely fine. Even with owner list view inheriting from member list view or list view [with a rewritten get context and get query set] it still shows up blank.

**Comment by Guneek** [comment]
Found the issue @LMarshallAfzal, its to do with button on each page, the lists load up when typed in as a url but not when redirected to from the buttons on owner, officer, etc.

**Comment by Guneek** [comment]
fixed by yours truly
