### ISSUE TITLE
Find a way to differentiate between different types of users

### ISSUE THREAD

**Issue by VimVoyager** [LMarshallAfzal/SEG-small-group-project#3]
@Kyal-Patel Alter user model to differentiate between user type so each user type can have different permissions.

**Comment by VinceWuu** [comment]
Applicants become members if membership is approved by an officer. So if I'm an applicant, before i am approved by the officer, what can I do or what pages can I visit?
Or should we just make the applicant page showing that 'waiting for approve' and only members can use the functions like a proper user. And add other functions that need higher permissions base on that.

**Comment by VimVoyager** [comment]
@VinceWuu If you read the epic,, it says applicants can view and edit the information they entered in the application/sign up form, so applicants should be able to go to a page which allows them to update thing like there bio, experience level, etc.
