### ISSUE TITLE
Redirect_URL_when_logged_in

### ISSUE THREAD

**Issue by VinceWuu** [LMarshallAfzal/SEG-small-group-project#7]
https://github.com/LMarshallAfzal/SEG-small-group-project/blob/8b076838e168a936c8785362126bf010b841f203/system/settings.py#L142

The setting for the system redirecting to the page 'feed' after user login.

**Comment by VimVoyager** [comment]
@VinceWuu We need to change that to what ever page they are permitted to view depending on what group they are in. So for officer it would go to officer_main. However, this will be different for applicants, members and owners.
